using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("ELW.Library.Math")]
[assembly: AssemblyDescriptionAttribute("Library for manipilations with expression.")]
[assembly: AssemblyCompanyAttribute("Elwood Home")]
[assembly: AssemblyConfigurationAttribute("net-3.5 release")]
[assembly: AssemblyVersionAttribute("0.1.0.2")]

